<?php
require_once '../includes/config.php';
require_once '../includes/functions.php';
require_once '../includes/db.php';

if (!is_logged_in()) {
    header("Location: ../login.php");
    exit;
}

$page_title = "CSS Grid Generator";
include '../templates/header.php';
?>
<div class="min-h-screen flex w-full bg-[#0B1120]">
    <?php
    $current_page = 'css_grid.php';
    include '../templates/sidebar.php';
    ?>

    <div class="flex-1 flex flex-col ml-64">
        <main class="flex-1 p-6 space-y-6">
            <h1 class="text-2xl font-bold">CSS Grid Generator</h1>
            <div class="grid grid-cols-1 lg:grid-cols-3 gap-6">
                <div class="card p-6 space-y-4">
                    <h2 class="font-bold">Settings</h2>
                    <div class="space-y-2">
                        <label class="block text-xs text-gray-400 uppercase">Columns</label>
                        <input type="number" id="cols" class="input" value="3" min="1" max="12">
                    </div>
                    <div class="space-y-2">
                        <label class="block text-xs text-gray-400 uppercase">Rows</label>
                        <input type="number" id="rows" class="input" value="3" min="1" max="12">
                    </div>
                    <div class="space-y-2">
                        <label class="block text-xs text-gray-400 uppercase">Gap (px)</label>
                        <input type="number" id="gap" class="input" value="10">
                    </div>
                </div>

                <div class="lg:col-span-2 space-y-4">
                    <div id="grid-preview" class="p-4 bg-[#111827] rounded-xl border border-[#1E293B] min-h-[400px] grid" style="grid-template-columns: repeat(3, 1fr); grid-template-rows: repeat(3, 1fr); gap: 10px;">
                        <!-- Items generated by JS -->
                    </div>

                    <div class="card p-6">
                        <label class="block text-sm font-medium text-gray-400 mb-2">Generated CSS</label>
                        <pre id="css-code" class="bg-[#0B1120] p-4 rounded-lg text-indigo-400 font-mono text-sm overflow-x-auto"></pre>
                    </div>
                </div>
            </div>

            <script>
                const grid = document.getElementById('grid-preview');
                const colsInput = document.getElementById('cols');
                const rowsInput = document.getElementById('rows');
                const gapInput = document.getElementById('gap');
                const cssCode = document.getElementById('css-code');

                function updateGrid() {
                    const c = colsInput.value;
                    const r = rowsInput.value;
                    const g = gapInput.value;

                    grid.style.gridTemplateColumns = `repeat(${c}, 1fr)`;
                    grid.style.gridTemplateRows = `repeat(${r}, 1fr)`;
                    grid.style.gap = `${g}px`;

                    grid.innerHTML = '';
                    for(let i=0; i < c*r; i++) {
                        const item = document.createElement('div');
                        item.className = 'bg-indigo-500/10 border border-indigo-500/30 rounded flex items-center justify-center text-indigo-500 font-bold';
                        item.textContent = i + 1;
                        grid.appendChild(item);
                    }

                    cssCode.textContent = `.grid-container {\n  display: grid;\n  grid-template-columns: repeat(${c}, 1fr);\n  grid-template-rows: repeat(${r}, 1fr);\n  gap: ${g}px;\n}`;
                }

                [colsInput, rowsInput, gapInput].forEach(el => el.addEventListener('input', updateGrid));
                updateGrid();
            </script>
        </main>
    </div>
</div>
<?php include '../templates/footer.php'; ?>
